branch-defaults:
  default:
    environment: forecastapp-server-dev
    group_suffix: null
global:
  application_name: forecastapp-server
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 17.09.1-ce
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
